#CREDENTIALS DATABASE
spring.datasource.url=${DB_URL_SB}
spring.datasource.username=${DB_USER_SB}
spring.datasource.password=${DB_PASSWORD_SB}

#DOMAIN FRONT
app.cors.allowed-origin=http://localhost:8080