spring.application.name=tur

#CREDENTIALS DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

#CONFIG DATABASE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#KEYS JWT
jwt.public.key=classpath:keys/public.pem
jwt.private.key=classpath:keys/private.pem

#SUPABASE CONFIG
supabase.url=${SUPABASE_URL}
supabase.anon-key=${SUPABASE_ANON_KEY}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}
supabase.bucket=${SUPABASE_BUCKET_NAME}
